server:
  port: 8888
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: tower-game
  #JDBC
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tower?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jef5re4g6e4
netty:
  port: 10101
game:
  verify: true
